In [3]:
import numpy as np

In [4]:
benimDizim=np.arange(0,15)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
benimDizim[5]

5

In [7]:
benimDizim[3:5]

array([3, 4])

In [8]:
benimDizim[3:5]=-5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi=np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
slicingDizisi = baskaDizi[4:9]

In [19]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [20]:
slicingDizisi[:]=700

In [21]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [22]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [23]:
ornekDizi=np.arange(0,24)

In [24]:
ornekdizikopyasi=ornekDizi.copy()

In [25]:
ornekdizikopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
ornekdizikopyaslicing=ornekdizikopyasi[3:6]

In [28]:
ornekdizikopyaslicing

array([3, 4, 5])

In [29]:
ornekdizikopyaslicing[:]=800

In [30]:
ornekdizikopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

matrix

In [32]:
benimListem= [[10,20,30],[15,25,35],[7,8,9]]

In [35]:
benimMatrixdizim=np.array(benimListem)

In [36]:
benimMatrixdizim

array([[10, 20, 30],
       [15, 25, 35],
       [ 7,  8,  9]])

In [37]:
benimMatrixdizim[0]

array([10, 20, 30])

In [38]:
benimMatrixdizim[1][2]

35

In [39]:
benimMatrixdizim[1,2]

35

In [42]:
benimMatrixdizim[0:,0]

array([10, 15,  7])

In [44]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [45]:
yeniMarix=np.array(yeniListe)

In [46]:
yeniMarix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
yeniMarix[[1,2,3]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

operasyonlar

In [52]:
yeniDizi=np.random.randint(1,100,20)

In [53]:
yeniDizi

array([59, 25, 71, 30, 75, 52, 99, 39, 53, 49, 83, 79, 75, 39, 78, 11, 78,
       29,  3, 63])

In [54]:
yeniDizi>24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True])

In [55]:
sonucDizisi=yeniDizi>23

In [56]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True])

In [57]:
yeniDizi

array([59, 25, 71, 30, 75, 52, 99, 39, 53, 49, 83, 79, 75, 39, 78, 11, 78,
       29,  3, 63])

In [59]:
yeniDizi[sonucDizisi]

array([59, 25, 71, 30, 75, 52, 99, 39, 53, 49, 83, 79, 75, 39, 78, 78, 29,
       63])

In [60]:
yeniDizi[yeniDizi<30]

array([25, 11, 29,  3])

In [61]:
sonDizi=np.arange(0,24)

In [62]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [67]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [68]:
sonDizi/sonDizi

C:\Users\90507\AppData\Local\Temp\ipykernel_21160\1954055075.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [70]:
np.max(sonDizi)

23