In [1]:
import numpy as np

Numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [6]:
type(np.array(benimListem))

numpy.ndarray

In [7]:
np.array(benimListem)

array([20, 30, 40])

In [8]:
matrixListesi=[[10,20,30],[15,25,35],[1,2,3]]

In [9]:
matrixListesi[1][0]

15

In [10]:
matrixListesi

[[10, 20, 30], [15, 25, 35], [1, 2, 3]]

In [11]:
np.array(matrixListesi)

array([[10, 20, 30],
       [15, 25, 35],
       [ 1,  2,  3]])

arange

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

zeros

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

linspace

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random

In [26]:
np.random.randn(4)

array([1.36770902, 1.02095415, 0.5712335 , 0.40894427])

In [27]:
np.random.randn(3,3)

array([[-0.35345779, -0.47566151, -1.0628929 ],
       [ 0.1321261 ,  1.5164969 , -2.30315045],
       [-0.19886611, -1.28962912, -0.38769749]])

In [45]:
np.random.randint(1,10)

5

In [47]:
np.random.randint(1,100,4)

array([49, 19, 70,  2])

In [60]:
benimNumpydizim=np.arange(20)

In [55]:
benimNumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [56]:
benimRandomdizim=np.random.randint(10,30,5)

In [57]:
benimRandomdizim

array([14, 13, 23, 28, 21])

Numpy dizi methodları

In [61]:
benimNumpydizim.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
benimNumpydizim.max()

19

In [64]:
benimRandomdizim.max()

28

In [65]:
benimRandomdizim.min()

13

In [66]:
benimRandomdizim.argmax()

3

In [67]:
benimRandomdizim.argmin()

1

In [72]:
benimNumpydizim.shape

(20,)

In [73]:
benimNumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])