In [1]:
import numpy as np

In [3]:
benimDizim=np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:5]

array([3, 4])

In [8]:
benimDizim[3:5]=-5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi=np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])